import string

LOGIN_REDIRECT_URL = "/lti/success"
BASE_CHARACTERS = string.ascii_letters + string.digits
SAFE_CHARACTERS = frozenset(BASE_CHARACTERS + '-')
KEY_LENGTH_RANGE = (6, 128)
NONCE_LENGTH = (6, 128)
SECRET_LENGTH_RANGE = (6, 128)
KEY_LENGTH = 16
SECRET_LENGTH = 64
USER_NAME_LENGTH=120
FIRST_NAME_LENGTH=50
LAST_NAME_LENGTH=50
EMAIL_LENGTH=50
CREATE_UNKNOWN_USER = True
SECRET_KEY = 'my super secret key'.encode('utf8')
